
[functions.publish-instagram-post]
enabled = true
verify_jwt = true
import_map = "./functions/publish-instagram-post/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/publish-instagram-post/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/publish-instagram-post/*.html" ]

[functions.check-scheduled-posts]
enabled = true
verify_jwt = false
import_map = "./functions/publish-instagram-post/deno.json" 
entrypoint = "./functions/check-scheduled-posts/index.ts"

[functions.transcribe-video]
enabled = true
verify_jwt = true
import_map = "./functions/transcribe-video/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/transcribe-video/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/transcribe-video/*.html" ]
